trigger:
- master

jobs:
- job: Build

  strategy:
    matrix:
      msvirtualcpp-2008expresssp1:
        name: msvirtualcpp-2008expresssp1

  pool:
    vmImage: 'windows-latest'

  steps:
  - script |
      cd $(name)
      choco pack
      ls
    displayName: Run choco pack
