parameters:
  name: ""

jobs:
- job: build_${{ replace(parameters.name, '-', '_') }}
  displayName: Build, Pack and Test ${{ parameters.name }}
  variables:
    VERSION_NUMBER: 1.2.3
  steps:
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.x'
  - task: gitversion/execute@0
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/release'))
    inputs:
      useConfigFile: true
      configFilePath: '.gitversion.master.yml'
    displayName: Set version using gitversion for master branch
  - powershell: |
      Set-PSDebug -Trace 1
      cd ${{ parameters.name }}
      $ver = "$(GitVersion.NuGetVersionV2)"
      if ($ver -ne "") {
        choco pack --version $ver
      } else {
        choco pack
      }
      cp *.nupkg $(Build.ArtifactStagingDirectory)/
      echo $(Build.ArtifactStagingDirectory)
      ls $(Build.ArtifactStagingDirectory)
    displayName: Run choco pack to build ${{ parameters.name }}
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: ${{ parameters.name }}
