parameters:
  name: ""

jobs:
- deployment: chocolateydeploy_${{ replace(parameters.name, '-', '_') }}
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
  displayName: Deploy ${{ parameters.name }} package to Chocolatey
  environment: chocolatey-publish-public
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: ${{ parameters.name }}
          displayName: 'Download nuget packages'

        - script: choco push *.nupkg --source https://push.chocolatey.org/ --apikey $(chocolate-api-key)
          displayName: 'Uploading chocolatey package'
