parameters:
  name: ""

stages:
- stage: ${{ replace(parameters.name, '-', '_') }}
  dependsOn: []
  pool:
    vmImage: 'windows-latest'
  displayName: Build, Test, and Deploy ${{ parameters.name }}
  jobs:
  - template: build.yaml
    parameters:
      name: ${{ parameters.name }}
  - template: test.yaml
    parameters:
      name: ${{ parameters.name }}
  - template: deploy.yaml
    parameters:
      name: ${{ parameters.name }}
- stage: deploy_${{ replace(parameters.name, '-', '_') }}
  dependsOn: ${{ replace(parameters.name, '-', '_') }}
  displayName: Deploy ${{ parameters.name }} to Chocolatey
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
  jobs:
  - template: chocolatey.yaml
    parameters:
      name: ${{ parameters.name }}
