parameters:
  name: ""
  cmakeGenName: ""

stages:
- stage: ${{ replace(parameters.name, '-', '_') }}
  dependsOn: []
  pool:
    vmImage: 'windows-latest'
  displayName: Build, Test, and Deploy ${{ parameters.name }}
  jobs:
  - template: build.yaml
    parameters:
      name: ${{ parameters.name }}
  - template: test.yaml
    parameters:
      name: ${{ parameters.name }}
      cmakeGenName: ${{ parameters.cmakeGenName }}
  - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/release') }}:
    - template: deploy.yaml
      parameters:
        name: ${{ parameters.name }}
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
  - stage: deploy_${{ replace(parameters.name, '-', '_') }}
    pool:
      vmImage: 'windows-latest'
    dependsOn: ${{ replace(parameters.name, '-', '_') }}
    displayName: Deploy ${{ parameters.name }} to Chocolatey
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    jobs:
    - template: chocolatey.yaml
      parameters:
        name: ${{ parameters.name }}
