parameters:
  name: ""
  cmakeGenName: ""

jobs:
- job: test_${{ replace(parameters.name, '-', '_') }}
  timeoutInMinutes: 120
  dependsOn: build_${{ replace(parameters.name, '-', '_') }}
  displayName: Test ${{ parameters.name }}
  steps:
  - task: Cache@2
    inputs:
      key: 'chocolatey2 | "$(Agent.OS)" | "${{ parameters.name }}" '
      path: $(CHOCOLATEY_CACHE_DIR)
      displayName: Chocolatey cache
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: ${{ parameters.name }}
      path: $(Build.ArtifactStagingDirectory)
  - script: choco source add -n=local -s "$(Build.ArtifactStagingDirectory)"
    displayName: Add chocolatey repo
  - script: choco config set cacheLocation "$(CHOCOLATEY_CACHE_DIR)"
    displayName: Set chocolatey cache dir
  - script: choco install -y --execution-timeout 7200 --pre ${{ parameters.name }}
    displayName: Install new chocolatey package ${{ parameters.name }}
  - script: |
      cat $(CHOCOLATEY_CACHE_DIR)\vs.log
      cat C:\ProgramData\chocolatey\logs\chocolatey.log
      fail >nul
    displayName: Debug
    condition: failed()
  - script: choco install -y cmake
    displayName: Install cmake
  - script: |
      @echo on
      cd tests
      mkdir build
      cd build
      echo "##vso[task.prependpath]%ProgramFiles%\\cmake\\bin"
      cmake.exe -G "${{ parameters.cmakeGenName }}" ..
      cmake.exe --build . --verbose
    displayName: Sanity check the compiler

